version: '3.9'

services:
  frontend:
    build: .
    container_name: coordinadora-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host